# Generated by Django 3.0.2 on 2020-01-04 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='alldjecipes.Creator'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alldjecipes.Recipe')),
            ],
        ),
    ]
