# Generated by Django 3.0.2 on 2020-01-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='alldjecipes/images/defaultimage.jpeg', upload_to='images/'),
        ),
    ]
