# Generated by Django 3.0.2 on 2020-01-06 19:14

import alldjecipes.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='contact',
            field=models.EmailField(default='', max_length=254, verbose_name=alldjecipes.users.models.ChefUser),
        ),
    ]
