# Generated by Django 3.0.2 on 2020-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='defaultimage.jpeg', upload_to='images/'),
        ),
    ]
