# Generated by Django 3.0.2 on 2020-01-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0002_auto_20200113_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
