# Generated by Django 3.0.2 on 2020-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0003_auto_20200109_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/alldjecipes/media/default/defaultimage.jpeg', upload_to='images/'),
        ),
    ]
