# Generated by Django 3.0.2 on 2020-01-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0004_auto_20200109_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='../../default/defaultimage.jpeg', upload_to='images/'),
        ),
    ]
