# Generated by Django 3.0.2 on 2020-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0006_auto_20200109_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='../../media/images/default/defaultimage.jpeg', upload_to='images/'),
        ),
    ]
