# Generated by Django 3.0.2 on 2020-01-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0008_auto_20200109_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='images/defaultimage.jpeg', upload_to='images/'),
        ),
    ]
