# Generated by Django 3.0.2 on 2020-01-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0011_auto_20200110_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='upvote',
        ),
    ]
